### ISSUE TITLE
Can't get Solver to running

### ISSUE THREAD

**Issue by TryAnixx** [jameswmccarty/signpost_puzz#1]
Hey,

i tried to get your solver running but i am encountering a issue.

![Screenshot 2024-07-26 200344](https://github.com/user-attachments/assets/0a4a7437-a725-441f-84a9-cfdfc5487ce0)

This is my Pattern

And this is my String Pattern:

```
solve('D-1,DR,R,U,D,DR,UR,UL,R,R,R,U,L,L,D,Star',(4,4))
```

The Console Output is empty.

What am i doing wrong?

Your Example in GitHub is working fine...

Example that works:
```
solve('DR-1,DR,R,DL,R,L,DL,UL,R,L,DR,DL,R,U,U-14,Star',(4,4))
```

**Comment by jameswmccarty** [comment]
Hello.  The inputs are brought into the puzzle grid top to bottom, left to right, as rows.  I think your went down the columns first.  I believe you just need to reorder your input as follows:

`solve('D-1,D,R,L,DR,DR,R,L,R,UR,R,D,U,UL,U,Star',(4,4))`
